#                                                                        #
# Default subroutes configuration for the TYPO3 package                  #
#                                                                        #

# add the following to your global Routes.yaml:
#-
#  name: 'Subroutes of the Semantic Package'
#  uriPattern: 'rdf/<SemanticSubroutes>'
#  subRoutes:
#    SemanticSubroutes:
#      package: Semantic

##
# RDF data endpoint

-
  name: 'RDF Data'
  uriPattern: 'data/{dataType}/{identifier}'
  defaults:
    '@package':    'SandstormMedia.Semantic'
    '@controller': 'RdfData'
    '@action':     'show'
    '@format':     'nt'

-
  name: 'RDF Identity'
  uriPattern: 'id/{dataType}/{identifier}'
  defaults:
    '@package':    'SandstormMedia.Semantic'
    '@controller': 'RdfIdentity'
    '@action':     'show'
-
  name: 'Description of all datasets using Void'
  uriPattern: 'void'
  defaults:
    '@package':    'SandstormMedia.Semantic'
    '@controller': 'Void'
    '@action':     'show'
    '@format':     'nt'
-
  name: 'Description of all datasets using Void, well-known shortcut'
  uriPattern: '.well-known/void'
  defaults:
    '@package':    'SandstormMedia.Semantic'
    '@controller': 'Void'
    '@action':     'wellKnown'
--
  name: 'RDF Enrichment test'
  uriPattern: 'enrich(/{@action})'
  defaults:
    '@package':    'SandstormMedia.Semantic'
    '@controller': 'ContinuousTextEnrichment'
    '@action':     'index'
